version: '3.8'
services:
    main:
        container_name: main
        build:
            context: .
            dockerfile: Dockerfile
        # command: 'php artisan serve --host=0.0.0.0'
        working_dir: /code
        volumes:
            - ./:/code
            -  /code/vendor
        ports:
            - 8181:8181
        depends_on:
            - mysql
    ui:
        container_name: ui
        build:
            context: .
            dockerfile: Dockerfileui
        working_dir: /app
        volumes:
            - ./:/app
            -  /app/node_modules
        ports:
            - 8001:8001
        depends_on:
            - main


    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_DATABASE: dolist
            MYSQL_USER: user
            MYSQL_ROOT: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
          - mysql
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
          PMA_ARBITRARY: 1
          MYSQL_ROOT_PASSWORD: root
        restart: always
        ports:
          - 8081:80
